

GENERAL:
  seed: 3407
  log_path: ./logs
  
TRAINING:
  num_k: 4
  batch_size: 128
  loss: MSE
  optimizer: adam
  learning_rate: 1.0e-4
  num_epochs: 200
  early_stopping:
    monitor: R
    patience: 20
    mode: max

MODEL:
  name: HFFST 
  num_genes: 250
  emb_dim: 512
  depth_t: 4
  depth_n: 2
  depth_s: 2
  depth_f: 1
  num_heads_t: 16
  num_heads_n: 16
  num_heads_s: 16
  num_heads_f: 8
  mlp_ratio_t: 1.0
  mlp_ratio_n: 1.0
  mlp_ratio_s: 1.0
  mlp_ratio_f: 4.0
  dropout_t: 0.1
  dropout_n: 0.3
  dropout_s: 0.1
  dropout_f: 0.1
  kernel_size: 3
  learning_rate: 0.0001
  backbone: 'resnet34'
  backbone_weights: weights\resnet34-b627a593.pth

DATASET:
  data_dir: dataset
  type: skin
  num_neighbors: 5
  t_global_dir: 'gt_features_224'
  neighbor_dir: 'n_features'
  radius: 224
