

GENERAL:
  seed: 101
  log_path: ./logs
  CoarseIter: 2
  MediumIter: 4
  
TRAINING:
  num_k: 8
  batch_size: 128
  loss: MSE
  optimizer: adam
  learning_rate: 1.0e-4
  num_epochs: 200
  early_stopping:
    monitor: R
    patience: 10
    mode: max

MODEL:
  name: HFFST 
  num_genes: 250
  emb_dim: 512
  depth_t: 3
  depth_n: 3
  depth_s: 3
  depth_f: 3
  num_heads_t: 8
  num_heads_n: 8
  num_heads_s: 8
  num_heads_f: 16
  mlp_ratio_t: 2.0
  mlp_ratio_n: 4.0
  mlp_ratio_s: 2.0
  mlp_ratio_f: 4.0
  dropout_t: 0.1
  dropout_n: 0.3
  dropout_s: 0.1
  dropout_f: 0.4
  kernel_size: 3
  learning_rate: 0.0001
  backbone: 'resnet34'
  backbone_weights: weights\resnet34-b627a593.pth
  
DATASET:
  data_dir: dataset
  type: stnet
  num_neighbors: 5

  t_global_dir: 'gt_features_224'
  neighbor_dir: 'n_features'

  radius: 224
  neighbor_rate: 1.2
